FROM node:18-alpine AS build

WORKDIR /app

COPY healthy-food-fe/package*.json ./
RUN npm ci

COPY healthy-food-fe/ ./
RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 5173
CMD ["nginx", "-g", "daemon off;"]
