import { ErrorMessages, StorageKeys, PaginationDefaults, TimeConstants, ActivityLevel, Formula, UnitSystem, BlogCategory } from '../types';

export const API_CONFIG = {
  BASE_URL: import.meta.env.VITE_API_URL || 'http://localhost:5000/api',
  TIMEOUT: 10000,
} as const;

export const PAGINATION = {
  DEFAULT_PAGE_SIZE: PaginationDefaults.DEFAULT_PAGE_SIZE,
  COMMENT_PAGE_SIZE: PaginationDefaults.COMMENT_PAGE_SIZE,
  REPLY_PAGE_SIZE: PaginationDefaults.REPLY_PAGE_SIZE,
} as const;

export const DEFAULTS = {
  CURRENT_PAGE: 1,
  SELECTED_CATEGORY: '',
  QUANTITY: 100,
  EDIT_QUANTITY: 100,
  EDIT_CALORIES: 0,
  SORT_BY: 'newest' as const,
} as const;

export const STORAGE_KEYS = {
  TOKEN: StorageKeys.TOKEN,
  USER: StorageKeys.USER,
  CURRENT_BMI: StorageKeys.CURRENT_BMI,
  CALORIE_DATA: StorageKeys.CALORIE_DATA,
} as const;

export const ERROR_MESSAGES = {
  NETWORK_ERROR: ErrorMessages.NETWORK_ERROR,
  FOOD_FETCH_FAILED: ErrorMessages.FOOD_FETCH_FAILED,
  CATEGORY_FETCH_FAILED: ErrorMessages.CATEGORY_FETCH_FAILED,
  BLOG_FETCH_FAILED: ErrorMessages.BLOG_FETCH_FAILED,
  COMMENTS_FETCH_FAILED: ErrorMessages.COMMENTS_FETCH_FAILED,
  REPLIES_FETCH_FAILED: ErrorMessages.REPLIES_FETCH_FAILED,
  COMMENT_CREATE_FAILED: ErrorMessages.COMMENT_CREATE_FAILED,
  COMMENT_UPDATE_FAILED: ErrorMessages.COMMENT_UPDATE_FAILED,
  COMMENT_DELETE_FAILED: ErrorMessages.COMMENT_DELETE_FAILED,
  LIKES_FETCH_FAILED: ErrorMessages.LIKES_FETCH_FAILED,
  LIKE_TOGGLE_FAILED: ErrorMessages.LIKE_TOGGLE_FAILED,
} as const;

export const TIME = {
  LOGIN_DELAY: TimeConstants.LOGIN_DELAY,
  ERROR_TIMEOUT: TimeConstants.ERROR_TIMEOUT,
  DEBOUNCE_DELAY: TimeConstants.DEBOUNCE_DELAY,
} as const;

export const UI = {
  ANIMATION_DURATION: 300,
  TRANSITION_DURATION: 200,
  DEBOUNCE_DELAY: 300,
  INFINITE_SCROLL_THRESHOLD: 100,
} as const;

export const ANIMATION = {
  DEFAULT_DELAY: 0.1,
  DEFAULT_DURATION: 0.3,
  STAGGER_DELAY: 0.1,
  LOADING_SPINNER_SIZE: 40,
  PRIMARY_COLOR: '#2196f3',
  PROGRESS_BAR_COLOR: '#2196f3',
} as const;

export const ACTIVITY_LEVELS: readonly ActivityLevel[] = [
  'Sedentary: Little or no exercise',
  'Lightly active: Light exercise/sports 1-3 days/week',
  'Moderately active: Moderate exercise/sports 3-5 days/week',
  'Very active: Hard exercise/sports 6-7 days a week',
  'Extra active: Very hard exercise/sports, physical job',
] as const;

export const FORMULAS: readonly Formula[] = [
  'mifflin',
  'harris',
  'katch',
] as const;

export const UNIT_SYSTEMS: readonly UnitSystem[] = [
  'metric',
  'imperial',
] as const;

export const BLOG_CATEGORIES: readonly BlogCategory[] = [
  'nutrition',
  'recipes',
  'fitness',
  'wellness',
  'tips',
  'news',
] as const;

export const BMI_CATEGORIES = {
  UNDERWEIGHT: 'Underweight',
  NORMAL: 'Normal weight',
  OVERWEIGHT: 'Overweight',
  OBESE: 'Obese',
} as const;

export const BMI_RANGES = {
  UNDERWEIGHT: { min: 0, max: 18.4 },
  NORMAL: { min: 18.5, max: 24.9 },
  OVERWEIGHT: { min: 25.0, max: 29.9 },
  OBESE: { min: 30.0, max: 100 },
} as const;

export const ACTIVITY_MULTIPLIERS: Record<ActivityLevel, number> = {
  'Sedentary: Little or no exercise': 1.2,
  'Lightly active: Light exercise/sports 1-3 days/week': 1.375,
  'Moderately active: Moderate exercise/sports 3-5 days/week': 1.55,
  'Very active: Hard exercise/sports 6-7 days a week': 1.725,
  'Extra active: Very hard exercise/sports, physical job': 1.9,
} as const;

export const VALIDATION = {
  PASSWORD_MIN_LENGTH: 6,
  PASSWORD_MAX_LENGTH: 50,
  NAME_MIN_LENGTH: 2,
  NAME_MAX_LENGTH: 50,
  EMAIL_MAX_LENGTH: 100,
  PHONE_MAX_LENGTH: 20,
  COMMENT_MAX_LENGTH: 1000,
  POST_TITLE_MAX_LENGTH: 200,
  POST_CONTENT_MAX_LENGTH: 10000,
  FILE_MAX_SIZE: 5 * 1024 * 1024, 
} as const;

export const ALLOWED_FILE_TYPES = [
  'image/jpeg',
  'image/jpg',
  'image/png',
  'image/webp',
] as const;

export const SORT_OPTIONS = [
  { value: 'newest', label: 'Mới nhất' },
  { value: 'oldest', label: 'Cũ nhất' },
  { value: 'most_liked', label: 'Nhiều like nhất' },
] as const;

export const CHART_COLORS = {
  PRIMARY: '#2196f3',
  SECONDARY: '#9c27b0',
  SUCCESS: '#4caf50',
  WARNING: '#ff9800',
  ERROR: '#f44336',
  INFO: '#00bcd4',
} as const;

export const THEME_COLORS = {
  PRIMARY: '#2196f3',
  SECONDARY: '#9c27b0',
  BACKGROUND: '#ffffff',
  SURFACE: '#f5f5f5',
  TEXT_PRIMARY: '#212121',
  TEXT_SECONDARY: '#757575',
  BORDER: '#e0e0e0',
  SHADOW: 'rgba(0, 0, 0, 0.1)',
} as const;

export const BREAKPOINTS = {
  MOBILE: 480,
  TABLET: 768,
  DESKTOP: 1024,
  LARGE_DESKTOP: 1200,
} as const;

export const Z_INDEX = {
  MODAL: 1000,
  DROPDOWN: 100,
  TOOLTIP: 200,
  HEADER: 50,
  FOOTER: 10,
} as const;

export const UI_TEXT = {
  
  LOADING: 'Loading...',
  UPLOADING: 'Uploading...',
  SELECT_IMAGE: 'Select Image',

  ENTER_EMAIL: 'Enter your email',
  ENTER_PASSWORD: 'Enter your password',
  ENTER_CURRENT_PASSWORD: 'Current password',
  ENTER_NEW_PASSWORD: 'New password',
  CONFIRM_NEW_PASSWORD: 'Confirm new password',
  ENTER_PHONE: 'Enter your phone number',
  ENTER_ADDRESS: 'Enter your address',
  ENTER_HEIGHT: 'Enter height...',
  ENTER_WEIGHT: 'Enter weight',
  ENTER_FULL_NAME: 'Full Name',
  ENTER_PHONE_NUMBER: 'Phone Number',

  ENTER_BLOG_TITLE: 'Nhập tiêu đề bài viết...',
  ENTER_BLOG_DESCRIPTION: 'Mô tả ngắn gọn về bài viết...',
  ENTER_BLOG_CONTENT: 'Viết nội dung bài blog của bạn...',
  ENTER_COMMENT: 'Viết bình luận...',
  EDIT_COMMENT: 'Chỉnh sửa bình luận...',
  ENTER_REPLY: 'Viết trả lời...',

  SEARCH_FOOD: 'Tìm kiếm thực phẩm...',
  SEARCH_POSTS: 'Tìm kiếm bài viết...',

  SELECT_DATE: 'Select date',
  DATE_FORMAT: 'DD.MM.YYYY',

  SELECT_GENDER: 'Select gender',
  SELECT_PROVINCE: 'Select province',
  SELECT_DISTRICT: 'Select district',

  QUANTITY_PLACEHOLDER: 'Quantity (g)',
  CALORIES_PLACEHOLDER: 'Calories',

  OTP_PLACEHOLDER: '000000',

  IMAGE_LOAD_FAILED: 'Avatar image failed to load. This might be due to server issues or file not found.',
  BMI_REFRESH_FAILED: 'Failed to refresh BMI',
  CATEGORIES_FETCH_FAILED: 'Error fetching categories',
  SCROLL_ERROR: 'Scroll to top error',
  FALLBACK_SCROLL_FAILED: 'Fallback scroll failed',
  FINAL_SCROLL_FAILED: 'Final scroll attempt failed',
  CREDENTIALS_PARSE_ERROR: 'Error parsing saved credentials',
  BLOG_IMAGE_LOAD_FAILED: 'Failed to load blog image',
  FOOD_IMAGE_LOAD_FAILED: 'Failed to load food image',
  MY_BLOG_IMAGE_LOAD_FAILED: 'Failed to load my blog image',

  COMMENTS_FETCH_ERROR: 'Error fetching comments',
  COMMENTS_LOAD_MORE_ERROR: 'Error loading more comments',
  COMMENT_CREATE_ERROR: 'Error creating comment',
  COMMENT_UPDATE_ERROR: 'Error updating comment',
  COMMENT_DELETE_ERROR: 'Error deleting comment',
  REPLY_CREATE_ERROR: 'Error creating reply',
  COMMENT_LIKE_TOGGLE_ERROR: 'Error toggling comment like',
  REPLY_LIKE_TOGGLE_ERROR: 'Error toggling reply like',

  // Blog specific text
  BLOG_IMAGE_PLACEHOLDER: 'Ảnh minh họa',
  ALL_CATEGORIES: 'Tất cả danh mục',
  NO_FOODS_FOUND: 'Không tìm thấy thực phẩm nào phù hợp với tiêu chí tìm kiếm.',
  NO_POSTS_FOUND: 'Không tìm thấy bài viết phù hợp với tiêu chí tìm kiếm của bạn.',
  LOADING_FOODS: 'Đang tải danh sách thực phẩm...',
  LOADING_POSTS: 'Đang tải bài viết...',
  LOADING_COMMENTS: 'Đang tải bình luận...',
  LOADING_MORE: 'Đang tải...',
  LOAD_MORE_COMMENTS: 'Tải thêm bình luận',
  SUGGESTION_CHANGE_FILTER: 'Thử thay đổi bộ lọc hoặc từ khóa tìm kiếm.',
  BLOG_TITLE: 'Bí Quyết Ăn Uống Lành Mạnh',
  MENU_LIST_TITLE: 'Danh Sách Thực Phẩm',
  MENU_DESCRIPTION: 'Khám phá thông tin dinh dưỡng chi tiết của các loại thực phẩm. Click vào thực phẩm để xem các cách chế biến và hàm lượng calo.',
  CREATE_BLOG_BUTTON: 'Viết Blog',
  CREATE_BLOG_TITLE: 'Viết blog mới',
  BACK_TO_LIST: '← Quay lại danh sách',
  BY_AUTHOR: 'Bởi',
  FOOD_DETAILS_TITLE: 'Chi tiết',
  FOOD_DETAILS_DESCRIPTION: 'rất giàu dinh dưỡng, chứa nhiều vitamin và khoáng chất. Mặc dù có hàm lượng carb cao hơn, những carbohydrate phức tạp giàu tinh bột này được chuyển hóa thành năng lượng và sẽ giúp bạn cảm thấy no lâu hơn. Hãy xem Bảng Calorie',
  FOOD_DETAILS_PRODUCTS: 'và Sản phẩm',
  FOOD_DETAILS_MORE_INFO: 'của chúng tôi dưới đây để biết thêm thông tin dinh dưỡng.',
  FOOD_NUTRITION_TABLE_FOOD: 'Food',
  FOOD_NUTRITION_TABLE_SERVING: 'Serving',
  FOOD_NUTRITION_TABLE_CALORIES: 'Calories',
  FOOD_PLACEHOLDER_ICON: '🍽️',
  PREVIOUS_BUTTON: 'Previous',
  NEXT_BUTTON: 'Next',
  PAGE_INFO: 'Page',
  OF_TEXT: 'of',
  
  // Comment specific text
  CONFIRM_DELETE_COMMENT: 'Bạn có chắc chắn muốn xóa bình luận này?',
  EDIT_BUTTON: 'Chỉnh sửa',
  RETRY_BUTTON: 'Thử lại',
  SENDING_COMMENT: 'Đang gửi...',
  SEND_COMMENT: 'Gửi bình luận',
  LOGIN_TO_COMMENT: 'Vui lòng đăng nhập để bình luận',
  SHOW_REPLIES: 'Hiển thị',
  HIDE_REPLIES: 'Ẩn',
  REPLIES_COUNT: 'trả lời',
  CANCEL_BUTTON: 'Hủy',
  SAVE_BUTTON: 'Lưu',
  REPLY_BUTTON: 'Trả lời',
  DELETE_BUTTON: 'Xóa',
  LIKE_BUTTON: 'Thích',
  
  // CreateBlog specific text
  CREATE_BLOG_MODAL_TITLE: 'Viết Blog mới',
  CREATE_BLOG_SUBTITLE: 'Chia sẻ kiến thức và kinh nghiệm của bạn',
  TITLE_LABEL: 'Tiêu đề',
  DESCRIPTION_LABEL: 'Mô tả ngắn',
  CATEGORY_LABEL: 'Danh mục',
  CONTENT_LABEL: 'Nội dung',
  REQUIRED_FIELD: '*',
  CHAR_COUNT: '/',
  TITLE_MAX_LENGTH: '100',
  DESCRIPTION_MAX_LENGTH: '200',
  CONTENT_MAX_LENGTH: '5000',
  CLICK_TO_SELECT_IMAGE: 'Click để chọn ảnh',
  SUPPORTED_FORMATS: 'Hỗ trợ: JPG, PNG, GIF (tối đa 5MB)',
  INVALID_IMAGE_ERROR: 'Vui lòng chọn file ảnh hợp lệ',
  POST_FAILED_ERROR: 'Đăng bài thất bại. Vui lòng thử lại!',
  CANCEL_BUTTON_TEXT: 'Hủy',
  POSTING_TEXT: 'Đang đăng...',
  POST_BUTTON_TEXT: 'Đăng bài',
  
  // BodyIndex specific text
  ENTER_HEIGHT_PLACEHOLDER: 'Enter height...',
  ENTER_WEIGHT_PLACEHOLDER: 'Enter weight',
  LOADING_BMI_DATA: 'Loading your BMI data...',
  LOADING_FOOD_RECOMMENDATIONS: 'Loading food recommendations...',
  NO_RECOMMENDATIONS_AVAILABLE: 'No recommendations available for your BMI category.',
  CALCULATE_BMI_FOR_RECOMMENDATIONS: 'Calculate your BMI to see personalized food recommendations.',
  RECOMMENDED_DISHES: 'Recommended Dishes',
  BASED_ON_BMI: 'Based on BMI:',
  PROTEIN_LABEL: 'Protein:',
  FAT_LABEL: 'Fat:',
  CARBS_LABEL: 'Carbs:',
  CALORIES_LABEL: 'Calories:',
  SERVING_LABEL: 'Serving:',
  ADD_TO_CALORIE_CALC: 'Add to Calorie Calc',
  CLOSE_BUTTON: '×',
  FOOD_CATEGORY_LABEL: 'Category:',
  UNKNOWN_CATEGORY: 'Unknown',
  CARBOHYDRATES_LABEL: 'Carbohydrates:',
  FIBER_LABEL: 'Fiber:',
  CAL_PER_UNIT: 'cal per',
  QUANTITY_UNIT: 'g',
  
  // CalorieCalculation specific text
  SELECT_CALCULATION_TABLE: 'Select calculation table',
  FOOD_TYPE_LABEL: 'Food Type',
  CALORIES_PER_100G: 'Calories (per 100g)',
  UNIT_LABEL: 'Unit',
  ACTION_LABEL: 'Action',
  ADD_TO_TABLE: 'Add to table',
  EDIT_BUTTON_TEXT: 'Edit',
  DELETE_BUTTON_TEXT: 'Delete',
  PREVIOUS_BUTTON_TEXT: 'Previous',
  NEXT_BUTTON_TEXT: 'Next',
  PAGE_INFO_TEXT: 'Page',
  EDIT_FOOD_ENTRY: 'Edit Food Entry',
  EDIT_ENTRY_NOTE: 'This entry represents the total quantity and calories for this food item on this date.',
  SAVE_CHANGES: 'Save Changes',
  DAILY_FOOD_STATISTICS: 'Daily Food Statistics',
  TOTAL_CALORIES: 'Total Calories',
  TOTAL_QUANTITY: 'Total Quantity',
  FOOD_ENTRIES: 'Food Entries',
  STATISTICS_BY_CATEGORY: 'Statistics by Category',
  TOP_FOODS_CONSUMED: 'Top Foods Consumed',
  PENDING_FOODS_FROM_BODYINDEX: 'Pending Foods from BodyIndex',
  ITEMS_LABEL: 'items',
  TOTAL_CALORIES_LABEL: 'total calories',
  ADD_ALL_TO_DAILY_TRACKING: 'Add All to Daily Tracking',
  CLEAR_ALL: 'Clear All',
  FOOD_NAME_LABEL: 'Food Name:',
  TOTAL_QUANTITY_LABEL: 'Total Quantity (g):',
  TOTAL_CALORIES_LABEL_2: 'Total Calories:',
  SHOWING_FIRST_10_ITEMS: 'Showing first 10 items. Use the dropdown above to select specific foods.',
  ENTRY_LABEL: 'Entry',
  ENTRIES_LABEL: 'entries',
  CAL_LABEL: 'cal',
  PER_100G: 'per 100g',
  
  // Dashboard specific text
  DASHBOARD_SUMMARY: 'Dashboard Summary',
  TODAYS_SUMMARY: "Today's Summary",
  THIS_WEEK: 'This Week',
  THIS_MONTH: 'This Month',
  TOP_CATEGORIES_TODAY: 'Top Categories Today',
  AVG_PER_DAY: 'Avg/Day:',
  FOOD_ITEMS_LABEL: 'Food Items:',
  TOTAL_ENTRIES_LABEL: 'Total Entries:',
  CALORIES_BY_FOOD_CATEGORY: 'Calories by Food Category',
  DAILY_CALORIE_INTAKE_BY_CATEGORY: 'Daily calorie intake by food category',
  DAILY_CALORIE_INTAKE_FOR_WEEK: 'Daily calorie intake for the selected week',
  WEEKLY_CALORIE_INTAKE_FOR_MONTH: 'Weekly calorie intake for the selected month',
  WEEK_LABEL: 'Week:',
  MONTH_LABEL: 'Month:',
  ITEMS_LABEL_2: 'items',
  CAL_LABEL_2: 'cal',
  PERCENTAGE_SYMBOL: '%',
  
  // CalorieIndex specific text
  DAILY_CALORIE_NEEDS_CALCULATOR: 'Daily Calorie Needs Calculator',
  UNIT_SYSTEM_LABEL: 'Unit System:',
  METRIC_LABEL: 'Metric',
  IMPERIAL_LABEL: 'Imperial',
  AGE_LABEL: 'Age',
  HEIGHT_LABEL: 'Height',
  WEIGHT_LABEL: 'Weight',
  GENDER_LABEL: 'Gender',
  FEMALE_LABEL: 'Female',
  MALE_LABEL: 'Male',
  BMR_FORMULA_LABEL: 'BMR Formula',
  MIFFLIN_ST_JEOR: 'Mifflin-St Jeor',
  HARRIS_BENEDICT: 'Harris-Benedict',
  KATCH_MCARDLE: 'Katch-McArdle',
  BODY_FAT_PERCENTAGE: 'Body Fat Percentage',
  ACTIVITY_LEVEL_LABEL: 'Activity Level',
  SELECT_ACTIVITY_LEVEL: 'Select activity level',
  CALCULATE_BUTTON: 'Calculate',
  RESET_BUTTON: 'Reset',
  SHOW_HISTORY: 'Show History',
  HIDE_HISTORY: 'Hide History',
  CALCULATION_HISTORY: 'Calculation History',
  YOUR_METABOLIC_INFORMATION: 'Your Metabolic Information',
  BMR_BASAL_METABOLIC_RATE: 'BMR (Basal Metabolic Rate)',
  TDEE_TOTAL_DAILY_ENERGY: 'TDEE (Total Daily Energy Expenditure)',
  WEIGHT_MANAGEMENT_GOALS: 'Weight Management Goals',
  WEIGHT_LOSS: 'Weight Loss',
  WEIGHT_GAIN: 'Weight Gain',
  MILD_LABEL: 'Mild',
  MODERATE_LABEL: 'Moderate',
  AGGRESSIVE_LABEL: 'Aggressive',
  KG_PER_WEEK: 'kg/week',
  CALORIES_LABEL_CALORIE: 'calories',
  ABOUT_BMR_AND_TDEE: 'About BMR and TDEE',
  CALCULATED_ON: 'Calculated on:',
  YEARS_LABEL: 'years',
  CM_LABEL: 'cm',
  IN_LABEL: 'in',
  KG_LABEL: 'kg',
  LB_LABEL: 'lb',
  PERCENT_SYMBOL_CALORIE: '%',
  MOST_ACCURATE_DESCRIPTION: 'Most accurate for most people',
  TRADITIONAL_FORMULA_DESCRIPTION: 'Traditional formula, slightly less accurate',
  REQUIRES_BODY_FAT_DESCRIPTION: 'Requires body fat percentage',
  SEDENTARY_OPTION: 'Sedentary: Little or no exercise',
  LIGHTLY_ACTIVE_OPTION: 'Lightly active: 1-3 times/week',
  MODERATELY_ACTIVE_OPTION: 'Moderately active: 4-5 times/week',
  VERY_ACTIVE_OPTION: 'Very active: 6 times/week or more',
  EXTRA_ACTIVE_OPTION: 'Extra active: Physical job or twice daily training',
  PROFESSIONAL_ATHLETE_OPTION: 'Professional athlete',
  TDEE_EXPLANATION: 'Your TDEE is the estimated number of calories you burn daily with your activity level',
  BMR_EXPLANATION: 'The Basal Metabolic Rate (BMR) is the number of calories your body needs while resting. This is the minimum amount of energy needed to keep your body functioning, including breathing and keeping your heart beating.',
  TDEE_EXPLANATION_2: 'Total Daily Energy Expenditure (TDEE) takes your BMR and adjusts it based on your activity level to estimate your total daily calorie needs.',
  CALCULATOR_USES_FORMULA: 'This calculator uses the',
  FORMULA_FOR_BMR_CALCULATION: 'formula for BMR calculation.',
  WEIGHT_LABEL_HISTORY: 'Weight:',
  BMR_LABEL_HISTORY: 'BMR:',
  TDEE_LABEL_HISTORY: 'TDEE:',
  VALID_AGE_ERROR: 'Please enter a valid age between',
  VALID_HEIGHT_ERROR: 'Please enter a valid height',
  VALID_WEIGHT_ERROR: 'Please enter a valid weight',
  BODY_FAT_REQUIRED_ERROR: 'Body fat percentage is required for Katch-McArdle formula',
  AND_TEXT: 'and',
  
  // HomePage specific text
  NUTRITION_PLATFORM_BADGE: 'Nền tảng dinh dưỡng #1 Việt Nam',
  SMART_NUTRITION_TITLE: 'Dinh dưỡng thông minh cho cuộc sống khỏe mạnh',
  PERSONALIZED_NUTRITION_SUBTITLE: 'Công cụ theo dõi dinh dưỡng cá nhân hóa giúp bạn đạt được mục tiêu sức khỏe',
  CHECK_BMI_BUTTON: 'Kiểm tra BMI',
  EXPLORE_BLOG_BUTTON: 'Khám phá blog',
  POPULAR_BADGE: 'Được yêu thích',
  SUGGESTED_MENU_TITLE: 'Thực đơn gợi ý hôm nay',
  VIEW_ALL_RECIPES: 'Xem tất cả công thức',
  FEATURES_BADGE: 'Tính năng',
  SMART_NUTRITION_TOOLS_TITLE: 'Công cụ theo dõi dinh dưỡng thông minh',
  BMI_CALCULATOR_TITLE: 'BMI Calculator',
  BMI_TRACKING_DESCRIPTION: 'Theo dõi chỉ số BMI và nhận lời khuyên dinh dưỡng được cá nhân hóa',
  CALORIE_TRACKING_TITLE: 'Calorie Tracking',
  CALORIE_TRACKING_DESCRIPTION: 'Ghi chép và theo dõi lượng calo tiêu thụ hàng ngày dễ dàng',
  FOOD_LOG_TITLE: 'Food Log',
  FOOD_LOG_DESCRIPTION: 'Lưu trữ lịch sử ăn uống và phân tích dinh dưỡng chi tiết',
  BLOG_COMMUNITY_TITLE: 'Blog Community',
  BLOG_COMMUNITY_DESCRIPTION: 'Chia sẻ kiến thức và kinh nghiệm về dinh dưỡng cùng cộng đồng',
  LATEST_POSTS_TITLE: 'Bài viết mới nhất',
  VIEW_ALL_POSTS: 'Xem tất cả bài viết',
  WELCOME_BACK_TITLE: 'Chào mừng trở lại!',
  CURRENT_BMI_LABEL: 'BMI hiện tại',
  TARGET_CALORIES_LABEL: 'Calo mục tiêu',
  TRACKING_DAYS_LABEL: 'Ngày theo dõi',
  MY_DASHBOARD_BUTTON: 'Dashboard của tôi',
  LOG_MEAL_BUTTON: 'Ghi chép bữa ăn',
  BREAKFAST_MEAL: 'Bữa sáng',
  LUNCH_MEAL: 'Bữa trưa',
  DINNER_MEAL: 'Bữa tối',
  SNACK_MEAL: 'Bữa phụ',
  KCAL_UNIT: 'kcal',
  PROTEIN_LABEL_HOMEPAGE: 'Protein',
  CARBS_LABEL_HOMEPAGE: 'Carbs',
  FATS_LABEL_HOMEPAGE: 'Fats',
  VIEW_DETAILS: 'Xem chi tiết',
  FIVE_MIN_READ: '5 phút đọc',
  READ_MORE: 'Đọc tiếp',
  BLOG_BADGE: 'Blog',
  
  // Profile specific text
  ADDRESS_TITLE: 'Address',
  ADD_ANOTHER_ADDRESS: '+ Add Another Address',
  UPDATE_ADDRESS_BUTTON: 'Update',
  ADDRESS_NOT_UPDATED: 'Address not updated yet',
  N_A_PLACEHOLDER: 'N/A',
  FULL_NAME_LABEL_PROFILE: 'Full Name',
  PHONE_NUMBER_LABEL_PROFILE: 'Phone Number',
  PROVINCE_LABEL: 'Province',
  DISTRICT_LABEL: 'District',
  TOWN_STREET_LABEL: 'Town/Street',
  DETAILS_LABEL: 'Details',
  SPECIFIC_ADDRESS_PLACEHOLDER: 'Specific address',
  BACK_BUTTON: 'Back',
  ADD_BUTTON: 'Add',
  SELECT_OPTION: 'Select',
  
  // ChangePassword specific text
  CHANGE_PASSWORD_TITLE: 'Change Password',
  CURRENT_PASSWORD_LABEL: 'Current Password',
  NEW_PASSWORD_LABEL: 'New Password',
  CONFIRM_NEW_PASSWORD_LABEL: 'Confirm New Password',
  CURRENT_PASSWORD_PLACEHOLDER: 'Current password',
  NEW_PASSWORD_PLACEHOLDER: 'New password',
  CONFIRM_NEW_PASSWORD_PLACEHOLDER: 'Confirm new password',
  PASSWORDS_NOT_MATCH_ERROR: 'New passwords do not match',
  PASSWORD_MIN_LENGTH_ERROR: 'New password must be at least 6 characters',
  PASSWORD_CHANGED_SUCCESS: 'Password changed successfully!',
  PASSWORD_CHANGE_FAILED: 'Failed to change password',
  PASSWORD_CHANGE_ERROR: 'An error occurred while changing password',
  SAVING_TEXT: 'Saving...',
  SAVE_PASSWORD_BUTTON: 'Save',
  
  // ProfileInfo specific text
  PROFILE_IMAGE_LABEL: 'Profile Image',
  NO_IMAGE_TEXT: 'No Image',
  EMAIL_LABEL_PROFILE: 'Email',
  GENDER_LABEL_PROFILE: 'Gender',
  BIRTHDAY_LABEL: 'Birthday',
  SELECT_GENDER_OPTION: 'Select Gender',
  MALE_OPTION: 'Male',
  FEMALE_OPTION: 'Female',
  OTHER_OPTION: 'Other',
  DAY_OPTION: 'Day',
  MONTH_OPTION: 'Month',
  YEAR_OPTION: 'Year',
  CANCEL_PROFILE_BUTTON: 'Cancel',
  UPDATE_PROFILE_BUTTON: 'Update',
  EDIT_PROFILE_BUTTON: 'Edit',
  SAVING_PROFILE: 'Saving...',
  PROFILE_UPDATED_SUCCESS: 'Profile updated successfully!',
  PROFILE_UPDATE_FAILED: 'Failed to update profile. Please try again.',
  FULL_NAME_REQUIRED: 'Full name is required',
  PHONE_REQUIRED: 'Phone number is required',
  GENDER_REQUIRED: 'Gender is required',
  FILE_SIZE_ERROR: 'File size must be less than 5MB',
  IMAGE_FILE_ERROR: 'Please select an image file',
  AVATAR_UPLOAD_SUCCESS: 'Avatar uploaded successfully!',
  AVATAR_UPLOAD_FAILED: 'Upload image failed! Please try again.',
  
  // Profile main component text
  PROFILE_MAIN_TITLE: 'Profile',
  EDIT_PROFILE_LABEL: 'Edit Profile',
  MY_PROFILE_TITLE: 'My Profile',
  ADDRESS_MENU_LABEL: 'Address',
  CHANGE_PASSWORD_MENU_LABEL: 'Change Password',
  MY_BLOGS_MENU_LABEL: 'My Blogs',
  AVATAR_ALT_TEXT: 'avatar',
  LOADING_TEXT: 'Đang tải...',
} as const;
